### ISSUE TITLE
Does not download from the local peers preferability

### ISSUE THREAD

**Issue by raeesiqbal** [feross/instant.io#110]
I tried to share a torrent today with my other computer via WebTorrent for Mac and instant.io. But because it was a popular torrent and other people were seeding it using WebTorrent and instant.io only connects with 10 peers, it did not connect to my seeding computer on the same network. Maybe it should iterate through different unconnected peers and [check if they are in local network](https://diafygi.github.io/webrtc-ips/), and if they are, it should connect with them.

**Comment by feross** [comment]
The [limitation on number of peers](https://github.com/feross/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js#L64) is just a temporary fix until Chrome 51 is released. There's a bad leak on OS X that causes 100% CPU usage. Once that's out, we can bump that number by a factor of 2 or 4, and then the chance that your local peer will be found will be higher.

But there's nothing we can really do if the server doesn't return the local peer because there are lots of other peers. That problem exists in normal bittorrent too, and repeatedly making requests to the tracker would not be a viable solution.

**Comment by feross** [comment]
Made an issue to track progress on that fix: https://github.com/feross/bittorrent-tracker/issues/152
