### ISSUE TITLE
Support magnet link as a url parameter to instant.io, to start sharing

### ISSUE THREAD

**Issue by dessalines** [feross/instant.io#127]
I'd love to be able to provide `instant.io` with a url param, to automatically start sharing a given magnet link.

The magnet link would have to be url encoded, but that wouldn't be a problem for any sites wanting to implement.

So something like:

`https://instant.io?magnet=magnet%3A%3Fxt%3Durn%3Abtih%3A6a9759bffd5c0af65319979fb7832189f4f3c35d%26dn%3Dsintel.mp4`

And it would load up instant.io and share that magnet link.

**Comment by Edward-Stryfe** [comment]
This feature is already actually part of the application. Instead of using ?magnet= like how the default share feature has instant.io/#infoHash do the same thing with the magnet link in place of the information hash. I tested it out both encoded and un-encoded and both worked perfectly.

https://instant.io/#magnet%3A%3Fxt%3Durn%3Abtih%3A6a9759bffd5c0af65319979fb7832189f4f3c35d%26dn%3Dsintel.mp4

That link should do just what your looking for. Same torrent and everything. If you wanted to make it even more shareable for sites like twitter you could put that url in a url shortener like tinyurl.com or bit.ly

**Comment by dessalines** [comment]
Ah sweet, thanks! It might be good to document this somewhere, either on the page itself, or on the github.

**Comment by Edward-Stryfe** [comment]
I think it's heavily implied since the functions of information hashes and magnet links are most of the time conjoined, since the application I'm fairly certain uses a list of default WSS trackers as is there isn't a need for the whole magnet link which is why there's only a share link that features just a straight hash. I could be wrong but that seems to be the case, but there's another active issue that is discussing the use of the default tracker list.

**Comment by dessalines** [comment]
An implied url hash? I had to ask to figure this out, it should definitely be documented.

**Comment by Edward-Stryfe** [comment]
Well personally as soon as I saw that the share link was nothing but an information hash I used the magnet link in place of it and I'm sure other users did to. There isn't really any natural place to document it on any of the webtorrent pages or instant.io. You could instead post another issue asking to add a "Magnet Share Link" which would be easier than documenting it somewhere. But since WT as a basis runs DHT there isn't too much point in adding trackers though they do help. It'll just result in possible the metadata arising quicker than it would have.

Not a bad thing but it's a bit of a fuss for a longer link just meant for sharing. I'm certain you can also use an http: link to a .torrent file as well. But since there's already a blob torrent it'd be pointless to post anywhere. 

If you really think this should be mentioned, make an issue in webtorrent-www which is the website and ask for them to mention this in the /docs page of the site.

**Comment by feross** [comment]
I'll add a short note to this repo's readme. Thanks for the issue and discussion 👍
