### ISSUE TITLE
Broken on Iceweasel

### ISSUE THREAD

**Issue by alexlincoln** [feross/instant.io#70]
The following error occurs when visiting the site on iceweasel

`TypeError: Rusha._core is not a constructor`

**Comment by feross** [comment]
What version of Iceweasel are you using?

Does the error happen in Firefox?

**Comment by alexlincoln** [comment]
I'm using version 31.8.0, and no the error only seems to be specific to Iceweasel

**Comment by feross** [comment]
Looks like the Rusha package (used for sha1 hashing) is broken on Iceweasel (i.e. Firefox 31). I did a bit of digging and filed a bug on the Rusha repo: https://github.com/srijs/rusha/issues/30

If the [Web Crypto Subtle API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) is available (Iceweasel/Firefox 34 and later) then that will be used instead of Rusha. If you use a newer version of Iceweasel, this problem should not exist. If Rusha fixes the bug, then it will start working in Firefox 31 as well.
