### ISSUE TITLE
Reduce ~20second wait to download files

### ISSUE THREAD

**Issue by szeloof** [feross/instant.io#81]
I've noticed that  downloading a file (from info hash) from instant.io it takes approximately 20 seconds each time to find peers and start receiving data from them. Is there any way to reduce this?

**Comment by feross** [comment]
Not sure why this happens. Let's keep this issue open to investigate.

**Comment by szeloof** [comment]
Agreed. While downloading I, I get `simple-websocket read: 2056 bytes +4ms` and then it pauses for about 20 seconds before starting the download. I've tried this in Firefox and Chrome on multiple devices. Oddly, this did not occur on a Chromebook.

**Comment by feross** [comment]
This is probably just the WebRTC handshake. The fact that the pause is after the websocket data has been read means that it's not the tracker server. I don't there's much we can do here, since it's network dependent and NAT dependent.

However, we can probably do work to make the initial websocket connection happen faster. I'll open an issue on WebTorrent for that.

**Comment by feross** [comment]
See https://github.com/feross/webtorrent/issues/574

**Comment by Robien** [comment]
I experience the same issue with my app using webtorrent and instant.io

If it's the WebRTC handshake, then why it is super-fast at webtorrent.io? Are there some voodoo magic?
I have seen that webtorrent.io is using the same way (twilio) to do the WebRTC handshake. Why one is fast and the other is slow ?

If it's magic, I want some.

**Comment by feross** [comment]
WebTorrent uses a web seed, and it uses a torrent file (which already contains the metadata) instead of a magnet link. That speeds up the startup time.
